# version: '3'


services:
  nginx:
    container_name: nginx
    hostname: lribette.42.fr
    build: ./requirements/nginx
    env_file: .env
    restart: unless-stopped
    depends_on:
      - wordpress
    volumes: 
      - wordpress:/var/www/wordpress
    networks: 
      - Inception
    ports: 
      - "443:443"

  mariadb:
    container_name: mariadb
    hostname: mariadb
    build: ./requirements/mariadb
    env_file: .env
    init: true
    restart: no
    volumes: 
      - mariadb_data:/var/lib/mysql
    networks: 
      - Inception
    expose:
      - "3306"
    healthcheck:
      test: "! mariadb-check"
      interval: 1s

  wordpress:
    container_name: wordpress
    hostname: wordpress
    build: ./requirements/wordpress
    env_file: .env
    restart: no
    depends_on:
      - mariadb
    volumes: 
      - wordpress:/var/www/wordpress
    networks: 
      - Inception
    expose:
      - "9000"
    # healthcheck:
    #   test: "nc wordpress:9000 -z"
    #   interval: 1s
    

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/lribette/data/mariadb     
      o: bind  

  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/lribette/data/wordpress
      o: bind

networks:
  Inception:
    name: Inception
    driver: bridge