version: '3'

services:
  nginx:
    build: ./requirements/nginx/
    image: nginx:latest
    ports:
      - "8080:443"
    volumes:
      - ./requirements/nginx/conf:/etc/nginx/templates
    environment:
      - NGINX_HOST=test.com
      - NGINX_PORT=80
    restart: always
    depends_on:
      - wordpress
    healthcheck:
      test: ["executable", "arg"]
      interval: 2s
      timeout: 30s
      retries: 5